name: Deploy to Hostinger
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      
      # Automation: Public ki files ko dist mein copy karna
      - name: Copy SEO files
        run: |
          cp public/sitemap.xml dist/
          cp public/robots.txt dist/

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ 
          server-dir: /  # <--- Isse change karke try karo
          protocol: ftp
          security: loose